## Activity 01: Use NumPy to compute the Mean, Median, and Variance

In this activity, you will consolidate the skills you've acquired in the last exercise and use NumPy to do some very basic mathematical calculations on our `normal_distribution` dataset.   
NumPy has a consistent API, so it should be rather easy to transfer your knowledge of the mean method to median and variance. 

#### Loading the dataset

In [1]:
# importing the necessary dependencies
import numpy as np

In [2]:
# loading the Dataset
dataset = np.genfromtxt('./data/normal_distribution.csv', delimiter=',')

In [16]:
import pandas as pd
pd.DataFrame(dataset)

0           1           2           3           4           5  \
0    99.149315  104.038527  107.435347   97.852307   98.749869   98.808334   
1    92.026288   97.104393   99.320669   97.245848   92.926751   92.656578   
2    95.662537   95.177501   90.933181  110.188895   98.800844  105.952977   
3    91.372946  100.967814  100.401183  113.420905  105.485088   91.660495   
4   101.208625  103.573031  100.286909  105.852694   93.371263  108.579804   
5   102.803871   98.296876   93.243764   97.241300   89.034527   96.283275   
6   106.717516  102.975856   98.457233  100.724189  106.397985   95.464934   
7    96.025483  102.823609  106.475518  101.347459  102.456518   98.747675   
8   105.303504   92.877308  103.192583  104.405183  101.293268  100.854471   
9   110.444843   93.871555  101.536365   97.653935   92.750486  101.720746   
10  101.351418  100.373722  106.647108  100.617428  105.032054   99.360000   
11   97.213157  107.028742  102.176421   96.746303   95.937992  102.623847   
12   95.659820  107.224824  107.191199  102.930395   85.988396   95.191843   
13  100.393035   92.010823   97.758876   93.188843  100.449403  108.094234   
14  103.152160  109.405232   93.839693   99.958279  101.834628   99.699828   
15  106.114550   88.802211   94.508179   94.593007  101.088305   96.346228   
16   96.782662   99.842516  104.034780  106.570527  105.136683  105.370119   
17  101.861862  103.617202   99.578599   99.488954  103.055414   98.659127   
18   97.495948   96.593855  104.638177  102.551986  105.860785   96.593778   
19   96.768148   91.677922  101.791328  101.207734   98.292440  101.838458   
20  106.890050  106.573646  102.266483  107.400646   99.943182  103.404121   
21   99.808731  101.639731  106.464765  110.439767  100.691562   99.995795   
22   96.100203   94.574217  100.804093  105.023899   98.613252   95.623593   
23   94.111769   99.623878  104.517864   97.627878   93.978535   98.751084   

             6           7  
0    96.819649   98.567832  
1   105.719785  101.231629  
2    98.374814  106.546543  
3   106.147284   95.087158  
4   100.794790   94.200197  
5   104.603448  101.134424  
6    94.353732  106.832738  
7    97.575443   92.574876  
8   101.222604  106.038688  
9    96.968512  103.291471  
10   98.870075   95.852842  
11  105.074753   97.595722  
12   91.320933  102.353140  
13   96.503429   99.586647  
14  103.052896  103.933840  
15   96.892443   98.071227  
16   99.075513  104.158998  
17   98.727741  104.705264  
18   93.046109   99.921600  
19   97.940469  102.206185  
20  106.382767   98.002530  
21  101.321137   94.762536  
22   97.997624  103.838525  
23  106.050425  100.077215

In [3]:
# looking at the first two rows of the dataset
dataset[:2]

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942]])

---

#### Mean

In [17]:
# calculate the mean of the third row
dataset[2].mean()

100.20466135250001

In [43]:
# calculate the mean of the last column
np.mean(dataset[:,-1:])

100.4404927375

In [23]:
# calculate the mean of the intersection of the first 3 rows and first 3 columns
dataset[:3,:3].mean()

97.87197312333333

---

#### Median

In [27]:
# calculate the median of the last row
np.median(dataset[-1:])

99.18748092

In [30]:
# calculate the median of the last 3 columns
np.median(dataset[-3:])

99.90226289

In [33]:
# calculate the median of each row
np.median(dataset, axis=1)

array([ 98.77910163,  97.17512034,  98.58782879, 100.68449836,
       101.00170737,  97.76908825, 101.85002253, 100.04756697,
       102.24292555,  99.59514997, 100.4955753 ,  99.8860714 ,
        99.00647994,  98.67276177, 102.44376222,  96.61933565,
       104.0968893 , 100.72023043,  98.70877396,  99.75008654,
       104.89344428, 101.00634942,  98.30543801,  99.18748092])

---

#### Variance

In [37]:
# calculate the variance of each column
np.var(dataset, axis=0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [41]:
# calculate the variance of the intersection of the last 2 rows and first 2 columns
dataset[-2:,:2].var()

4.674691991769191

The values of the variance might seem a little bit strange at first.   
You can always go back to the topic that gives you a quick statistical overview to recap what you've learned so far.   

> **Note:**   
Just remember, the variance is not the standard deviation.   

Try calculation the standard deviation with NumPy to get a more descriptive value when comparing it to our dataset

In [42]:
# calculate the standard deviation for the dataset
dataset.std()

4.838197554269257